name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy with Docker Compose
        run: |
          cd /opt/device-service
          git pull origin master
          docker compose up -d --build
          docker image prune -f
