name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with Docker Compose
        run: |
          cd $GITHUB_WORKSPACE
          docker compose up -d --build
          docker image prune -f
